[variables]
NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["php82", "nodejs_22", "composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache"
]